-- Phase 3: saving orders safely.

-- One checkout attempt = one key, generated by the browser. A double tap or a network retry sends the
-- same key, and the UNIQUE index turns the second insert into "return the order we already saved".
ALTER TABLE orders ADD COLUMN idempotency_key uuid;
CREATE UNIQUE INDEX orders_idempotency_key_uq ON orders (idempotency_key);

-- Snapshots: what the customer saw at the moment of ordering, even if the customer record,
-- the area name or the fee changes later.
ALTER TABLE orders ADD COLUMN customer_name text;
ALTER TABLE orders ADD COLUMN customer_phone text CHECK (customer_phone ~ '^01[0125][0-9]{8}$');
ALTER TABLE orders ADD COLUMN area_name text;

-- Order e-mail to the shop: when it went out, how many times it failed.
ALTER TABLE orders ADD COLUMN notified_at timestamptz;
ALTER TABLE orders ADD COLUMN notify_attempts integer NOT NULL DEFAULT 0;

-- Hash of the buyer's IP (never the IP itself), for abuse checks.
ALTER TABLE orders ADD COLUMN ip_hash text;

CREATE INDEX orders_phone_recent_idx ON orders (customer_phone, created_at DESC);
CREATE INDEX orders_unnotified_idx ON orders (created_at) WHERE notified_at IS NULL;

-- Fixed-window counters for rate limits (checkout, order lookup). Small table; old rows are pruned.
CREATE TABLE rate_limits (
  key           text NOT NULL,
  window_start  timestamptz NOT NULL,
  count         integer NOT NULL DEFAULT 0,
  PRIMARY KEY (key, window_start)
);
CREATE INDEX rate_limits_window_idx ON rate_limits (window_start);
