// Generated by scripts/make-blur.py — do not edit by hand.
// Tiny blurred previews shown while each photo loads.
export const BLUR: Record<string, string> = {
  "/images/burgundy-hanger.jpg": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAA8AAwBSJZwC7ADp7zIGjoAA/pscBhWpG0Xv5hT3rWvf9KHXlghc+z5ZM2KsWIHtA2sCHT+T7fGY0Tywxdu5AJBwuh43OTvs11wYAAA=",
  "/images/burgundy-hd-collar.jpg": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoMAA8AAwBSJQBOgCBuiiEPAAD+7SLGaHXigtOE+cYQiGKeQZJ/1RsmjrWQpQMczL93JRGy1LHKwmvmrMKmvF4YIopV03h+QEH6kIvL5AeJpUAA",
  "/images/burgundy-hd-flatlay.jpg": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAA8AAwBSJQAAYv/v/JSY6AAA/annJfctbEfzHZCG6RBgqsEvOogq+W4thn8QqDTddqbQSgCo88bzYkAAAA==",
  "/images/burgundy-hd-full.jpg": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoMAA8AAwBSJQBOgCLs2plNCX0AAPw90P5Vq2lrss/77dp5aJY6QqHTPxQkVFh/jxA37TofYATLpq3Mt1AEvGhvxmgYu9kGcmbVoAAA",
  "/images/burgundy-hd-lean.jpg": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoMAA8AAwBSJYwCdADc7645fcPyAP7s6aVRBAvhZVNHK5Rc1oVP5/E7PAYa/hZHfNPoDLpnGSq4/V5/d/tFYm+3s5ddXQwA",
  "/images/burgundy-styled.jpg": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoMAA8AAwBSJYwCdAEXZyzGilF64AD++LpQ5y+HwPDpCjz/b+KMtBh9JEzuzB96WRPvy4crQl1mF8lhbBor02SeB99+h+55lnL0I0GTZX7VuMPCfBENPv4njTcAAA==",
  "/images/craft-sleeve-tall.jpg": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAA8AAwBSJYwCdAD7EsfM0AAA/uZ6nEbER9snpWYZF23saKoDAeyu+AjQquXW9IzQCzSFyKtIyVBnHF6bzm17X2RZiLn/YBYAAA==",
  "/images/craft-sleeve-wide.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoMAAcAAwBSJZQCdAEXw9UojXogAP7RWc6fc6dPK2ZowL47HflqFhoy68nXACoPSDu/RwAA",
  "/images/cream-hd-chest.jpg": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoMAA8AAwBSJYwCdAECprqxINU3AADMo6uner5NUvEC44ZRqje4OGw3Zp0hlS3Y7K8M5stv5Z6csnD2X7C0cAyKWVyRBqKFIHLkMwg+H3qAdvNNAAA=",
  "/images/cream-hd-model.jpg": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAA8AAwBSJYwCdADcIZm5hGAA/vNfwAO8HDoFv4TPor+yF60GpkkIMSr/6zunDyk1PpaJzmFD/EMy2NyBsqbIQXydcil+LEDjVBiWoAA=",
  "/images/cream-hd-sleeve.jpg": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMAA8AAwBSJQBOgB9gSCIehoAA/cPeHQwe3awZ7+LMeAKgX3DloAvbha7D27qU0yZtUaVStuTVl1bGubY1IIMaTM9lqk/FvsoJYaAA",
  "/images/cream-styled.jpg": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAA8AAwBSJZwAAxUzPgrdIFAA/vizzvxTcSUHS2tUUhmyGxV3ANP4x0yGMKmNAxBzTBZIYm903vEvAAA=",
  "/images/hero-pair.jpg": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoKAA8AAwBSJQBOgCLMgr4/ra4AAPwjEx74M6FypdjRV7YaLqmL4pU/ShcN4VthDL9iJmbkyh5MZEoBlQCRPA6b9v/PwlggeAHFhh3YjwwAAA==",
};

/** Background for a photo's frame: the tiny preview, stretched smoothly by the browser into a soft blur.
 * Shows instantly; the real photo covers it when loaded. No blur filter, so no extra work for the phone. */
export function preview(src: string): { backgroundImage: string; backgroundSize: string; backgroundPosition: string } | undefined {
  const data = BLUR[src];
  return data ? { backgroundImage: `url(${data})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined;
}
