// Generated by scripts/make-blur.py — do not edit by hand.
// The two main colours of each photo (top, bottom), used as a soft gradient while it loads.
export const TONES: Record<string, [string, string]> = {
  "/images/burgundy-hanger.jpg": ["#867f7b", "#6a615d"],
  "/images/burgundy-hd-collar.jpg": ["#867c77", "#95938e"],
  "/images/burgundy-hd-flatlay.jpg": ["#827074", "#715a5e"],
  "/images/burgundy-hd-full.jpg": ["#8f857f", "#a5a199"],
  "/images/burgundy-hd-lean.jpg": ["#897f7a", "#8c827e"],
  "/images/burgundy-styled.jpg": ["#ac9e9c", "#b3a8a3"],
  "/images/craft-sleeve-tall.jpg": ["#ab9c90", "#bbb1a8"],
  "/images/craft-sleeve-wide.jpg": ["#b8ada2", "#b8aea5"],
  "/images/cream-hd-chest.jpg": ["#bcb2ac", "#cbc6bd"],
  "/images/cream-hd-model.jpg": ["#8a847d", "#a39f95"],
  "/images/cream-hd-sleeve.jpg": ["#a39283", "#bab0a6"],
  "/images/cream-styled.jpg": ["#e8e3e0", "#d8d2cc"],
  "/images/hero-pair.jpg": ["#a59794", "#898889"],
};

/** Background for a photo's frame while the photo loads: a soft gradient of the photo's own colours. */
export function preview(src: string): { backgroundColor: string; backgroundImage: string } | undefined {
  const t = TONES[src];
  return t ? { backgroundColor: t[0], backgroundImage: `linear-gradient(180deg, ${t[0]}, ${t[1]})` } : undefined;
}
