"""Prepares every photo ahead of time so no image is ever converted while a customer waits.

For each public/images/<name>.jpg it writes:
  public/img/<name>-<width>.webp  for every width the site asks for (see next.config.ts images.deviceSizes/imageSizes)
and lib/blur.ts with a tiny (32 px) WebP of each photo, shown softly scaled up while the real photo arrives.

Run after adding or changing photos (a changed photo must get a NEW file name):
    python3 scripts/make-images.py
A test fails if this was forgotten."""
import base64, glob, io, os
from PIL import Image

WIDTHS = [96, 192, 480, 828, 1200, 1600]  # keep in sync with next.config.ts (imageSizes + deviceSizes)
QUALITY = 74
os.makedirs("public/img", exist_ok=True)

previews = []
for path in sorted(glob.glob("public/images/*.jpg")):
    name = os.path.basename(path)[:-4]
    src = Image.open(path).convert("RGB")
    for w in WIDTHS:
        out = f"public/img/{name}-{w}.webp"
        if os.path.exists(out) and os.path.getmtime(out) >= os.path.getmtime(path):
            continue
        im = src if src.width <= w else src.resize((w, round(src.height * w / src.width)), Image.LANCZOS)
        im.save(out, "WEBP", quality=QUALITY, method=6)
    tiny = src.copy()
    tiny.thumbnail((32, 40), Image.LANCZOS)
    buf = io.BytesIO()
    tiny.save(buf, "WEBP", quality=55, method=6)
    previews.append(f'  "/images/{name}.jpg": "data:image/webp;base64,{base64.b64encode(buf.getvalue()).decode()}",')

ts = (
    "// Generated by scripts/make-images.py — do not edit by hand.\n"
    "// A tiny copy of each photo, shown softly scaled up in the photo's frame until the real photo arrives.\n"
    "export const PREVIEWS: Record<string, string> = {\n" + "\n".join(previews) + "\n};\n\n"
    "/** Background for a photo's frame: the photo itself, tiny and smoothly scaled (looks like a soft blur). */\n"
    "export function preview(src: string): { backgroundImage: string; backgroundSize: string; backgroundPosition: string } | undefined {\n"
    "  const data = PREVIEWS[src];\n"
    "  return data ? { backgroundImage: `url(${data})`, backgroundSize: \"cover\", backgroundPosition: \"center\" } : undefined;\n"
    "}\n"
)
open("lib/blur.ts", "w").write(ts)
total = sum(os.path.getsize(f) for f in glob.glob("public/img/*.webp"))
print(f"{len(previews)} photos, {len(glob.glob('public/img/*.webp'))} files, {total // 1024} KB; previews {len(ts)} bytes")
