"""Builds lib/blur.ts: for every photo in public/images, a soft two-tone gradient (top colour → bottom
colour of that photo). Shown in the photo's frame while it loads, so the space never looks empty or
pixelated; the photo then fades in on top. Run after adding or changing photos:
    python3 scripts/make-blur.py
The test "every photo has a preview" fails if this was forgotten."""
import glob, os
from PIL import Image

PAPER = (243, 240, 232)  # site background tone; previews lean 30% toward it so they feel light, not heavy

def avg(im):
    r, g, b = im.resize((1, 1), Image.LANCZOS).getpixel((0, 0))
    r, g, b = (round(c * 0.7 + p * 0.3) for c, p in zip((r, g, b), PAPER))
    return f"#{r:02x}{g:02x}{b:02x}"

rows = []
for path in sorted(glob.glob("public/images/*.jpg")):
    im = Image.open(path).convert("RGB")
    w, h = im.size
    top, bottom = avg(im.crop((0, 0, w, h // 2))), avg(im.crop((0, h // 2, w, h)))
    rows.append(f'  "/images/{os.path.basename(path)}": ["{top}", "{bottom}"],')

out = (
    "// Generated by scripts/make-blur.py — do not edit by hand.\n"
    "// The two main colours of each photo (top, bottom), used as a soft gradient while it loads.\n"
    "export const TONES: Record<string, [string, string]> = {\n" + "\n".join(rows) + "\n};\n\n"
    "/** Background for a photo's frame while the photo loads: a soft gradient of the photo's own colours. */\n"
    "export function preview(src: string): { backgroundColor: string; backgroundImage: string } | undefined {\n"
    "  const t = TONES[src];\n"
    "  return t ? { backgroundColor: t[0], backgroundImage: `linear-gradient(180deg, ${t[0]}, ${t[1]})` } : undefined;\n"
    "}\n"
)
open("lib/blur.ts", "w").write(out)
print(f"{len(rows)} photos, {len(out)} bytes")
