"""Builds lib/blur.ts: a tiny blurred preview (≈150 bytes) of every photo in public/images, shown
instantly while the real photo loads (no blank flash). Run after adding or changing photos:
    python3 scripts/make-blur.py
The test "every photo has a blur preview" fails if this was forgotten."""
import base64, glob, io, os
from PIL import Image

rows = []
for path in sorted(glob.glob("public/images/*.jpg")):
    im = Image.open(path).convert("RGB")
    im.thumbnail((12, 15))
    buf = io.BytesIO()
    im.save(buf, "WEBP", quality=45, method=6)  # ~120 bytes each; every current browser shows WebP
    src = "/images/" + os.path.basename(path)
    rows.append(f'  "{src}": "data:image/webp;base64,{base64.b64encode(buf.getvalue()).decode()}",')

out = (
    "// Generated by scripts/make-blur.py — do not edit by hand.\n"
    "// Tiny blurred previews shown while each photo loads.\n"
    "export const BLUR: Record<string, string> = {\n" + "\n".join(rows) + "\n};\n\n"
    "/** Props for next/image: a blur-up preview when one exists. */\n"
    "export function blur(src: string): { placeholder?: \"blur\"; blurDataURL?: string } {\n"
    "  const data = BLUR[src];\n"
    "  return data ? { placeholder: \"blur\", blurDataURL: data } : {};\n"
    "}\n"
)
open("lib/blur.ts", "w").write(out)
print(f"{len(rows)} previews, {len(out)} bytes")
